### ISSUE TITLE
[Front end] Integrate Moon Email Sign Up/In

### ISSUE THREAD

**Issue by hellf17** [0xBcamp/Alfaqi-janus-dragon#3]
We need a credential system for our app.
We will be utilizing the Moon wallet abstraction for enabling using to generate a wallet with his email and a password.

**Comment by jilt** [comment]
I thought we didn't have to integrate moon, will be catching up with this if needed

**Comment by hellf17** [comment]
We will use it as the credential system for our app

> I thought we didn't have to integrate moon, will be catching up with this if needed
